server:
  port: 8888
spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FabioNazario/config-repo
          default-label: main
logging:
  config: https://raw.githubusercontent.com/FabioNazario/config-repo/main/logback.xml
